### Save Hall 1
POST http://localhost:8080/hall/create
Content-Type: application/json

{
  "name": "Sala 1",
  "venue": {
    "id": 1,
    "address": "Via uno",
    "city": "Bari",
    "isIndoors": true,
    "name": "Politeama di Bari"
  }
}

### Save Hall 2
POST http://localhost:8080/hall/create
Content-Type: application/json

{
  "name": "Sala 2",
  "venue": {
    "id": 1,
    "address": "Via uno",
    "isIndoors": true,
    "name": "Politeama di Bari"
  }
}

### Save Hall 3
POST http://localhost:8080/hall/create
Content-Type: application/json

{
  "name": "Sala 3",
  "venue": {
    "id": 1,
    "address": "Via uno",
    "isIndoors": true,
    "name": "Politeama di Bari"
  }
}